apiVersion: v1
kind: Service
metadata:
  name: relayserver
spec:
  type: ClusterIP
  selector:
    type: relayserver
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: https
    - protocol: TCP
      port: 1701
      targetPort: 1701
      name: metricsport
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---

apiVersion: v1
kind: Pod

metadata:
  name: relayserver
  labels:
    type: relayserver
    role: relayserver
spec:
  restartPolicy: Never
  containers:
    - name: relayserver
      image: theotw/k8srelaytest:dev
      command:
        - ./run_relay_server_coverage.sh
      imagePullPolicy: Always
      env:
        - name: NATS_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: relay-config
              key: nats_url
