apiVersion: v1
kind: Service
metadata:
  name: relaylet
spec:
  type: ClusterIP
  selector:
    type: relaylet
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
      name: http
---

apiVersion: v1
kind: Pod

metadata:
  name: relaylet
  labels:
    type: relaylet
    role: relaylet
spec:
  restartPolicy: Never
  serviceAccountName: k8srelay-sa
  containers:
    - name: relaylet
      image: theotw/k8srelaytest:dev
      command:
        - ./scripts/run_relaylet_coverage.sh
      env:
        - name: NATS_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: relay-config
              key: nats_url
