apiVersion: v1
kind: Service
metadata:
  name: relayserver
spec:
  type: NodePort
  selector:
    type: relayserver
  ports:
    - protocol: TCP
      port: 8443
      nodePort: 30883
      targetPort: 8443
---

apiVersion: v1
kind: Pod

metadata:
  name: relayserver
  labels:
    type: relayserver
    role: relayserver
spec:
  restartPolicy: Never
  containers:
    - name: relayserver
      image: theotw/k8srelayserver:latest
      imagePullPolicy: Always
      env:
        - name: NATS_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: relay-config
              key: nats_url
