apiVersion: v1
kind: Service
metadata:
  name: relaylet
spec:
  type: NodePort
  selector:
    type: relaylet
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
---

apiVersion: v1
kind: Pod

metadata:
  name: relaylet
  labels:
    type: relaylet
    role: relaylet
spec:
  restartPolicy: Never
  containers:
    - name: relaylet
      image: theotw/k8srelaylet:latest
      imagePullPolicy: Always
      env:
        - name: NATS_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: relay-config
              key: nats_url
