name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"
  workflow_dispatch:
    branches: '*'

jobs:
  build_and_test:
    name: CICD tests
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      CA_SUB: ${{ vars.CA_SUB }}
      IMAGE_REPO: ${{ vars.IMAGE_REPO }}
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy
          go install github.com/t-yuki/gocover-cobertura@latest
          go install github.com/wadey/gocovmerge@latest
          mkdir -p out

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          config: testfiles/kind-config.yaml
      - name: Validate Kind Cluster
        run: |
          echo "let kind get up and running"
          sleep 120
          echo "kubectl get nodes -o wide" 
          kubectl get nodes -o wide
          echo "kubectl get storageclasses"
          kubectl get storageclasses
          echo "kubectl  get serviceaccount"
          kubectl  get serviceaccount


      - name: Get current date
        id: date
        run: |
          export BASEVERSION=$(cat version.txt)
          export BUILD_VERSION=$BASEVERSION.$(date +'%Y%m%d%H%M')
          echo $BUILD_VERSION > out/BUILD_VERSION.txt
          cd ..

      - name: Build image
        run: |
          export BUILD_VERSION=$(cat out/BUILD_VERSION.txt)
          export IMAGE_TAG=$BUILD_VERSION
          echo $BUILD_VERSION
          make allimages

      - name: Tag and push image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Push commented out"
          export BUILD_VERSION=$(cat out/BUILD_VERSION.txt)
          export IMAGE_TAG=$BUILD_VERSION
          echo $BUILD_VERSION 
          
          docker login $IMAGE_REPO -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          make push


      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cicd-test-results
          path: |
            out/*
          retention-days: 5