name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: "*"
  workflow_dispatch:
    branches: '*'

jobs:
  build_and_test:
    name: CICD tests
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      CA_SUB: ${{ vars.CA_SUB }}
      IMAGE_REPO: ${{ vars.IMAGE_REPO }}
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy
          go install github.com/t-yuki/gocover-cobertura@latest
          go install github.com/wadey/gocovmerge@latest
          mkdir -p out

      - name: Unit / L1 Test
        run: |
          #top level out needed for mounting
          mkdir -p out
          go install github.com/jstemmer/go-junit-report@latest
          #lower level out.  we want both
          mkdir -p out
          export NATS_URL=nats://localhost:30220
          go test -v -coverpkg=github.com/theotw/k8srelay/pkg/... -coverprofile=out/unit_coverage.out github.com/theotw/k8srelay/pkg/... > out/l1_out.txt 2>&1
          cat out/l1_out.txt | go-junit-report > out/l1_report.xml 
          cat out/l1_out.txt
          ls -l out/
          cat out/l1_report.xml
          pwd        
      
      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          config: testfiles/kind-config.yaml
      - name: Validate Kind Cluster
        run: |
          echo "let kind get up and running"
          sleep 120
          echo "kubectl get nodes -o wide" 
          kubectl get nodes -o wide
          echo "kubectl get storageclasses"
          kubectl get storageclasses
          echo "kubectl  get serviceaccount"
          kubectl  get serviceaccount
          kubectl create ns test
          kubectl -n test apply -f testfiles/sa.yaml
          kubectl -n test apply -f testfiles/relay-config.yaml
          kubectl -n test apply -f testfiles/nats.yaml
          
          


      - name: Get current date
        id: date
        run: |
          export BASEVERSION=$(cat version.txt)
          export BUILD_VERSION=$BASEVERSION.$(date +'%Y%m%d%H%M')
          echo $BUILD_VERSION > out/BUILD_VERSION.txt
          cd ..

      - name: Build image
        run: |
          export BUILD_VERSION=$(cat out/BUILD_VERSION.txt)
          export IMAGE_TAG=$BUILD_VERSION
          echo $BUILD_VERSION
          make allimages

      - name: Tag and push image
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Push commented out"
          export BUILD_VERSION=$(cat out/BUILD_VERSION.txt)
          export IMAGE_TAG=$BUILD_VERSION
          echo $BUILD_VERSION 
          echo $IMAGE_REPO 
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          docker login $IMAGE_REPO -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          make tag
          


      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cicd-test-results
          path: |
            out/*
          retention-days: 5